/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElLoading: typeof import('element-plus')['ElLoading'] 
  const ElMessage: typeof import('element-plus')['ElMessage']
}
